clone_depth: 5

environment:
  access_token:
    secure: f1KvGZaowYTz1y8cJs8G+w29KWKnr60QNE0Bmla+mvak0vphwF1iGIOUHehJXC8R
  matrix:
    - PYTHON: "C:\\Python36-x64"

skip_commits:
  message: /Update Static Site/

install:
  - set PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%
  - python --version
  - pip install Pillow
  - pip install opencv-python

build_script:
  - git config --global credential.helper store
  - ps: Add-Content "$HOME\.git-credentials" "https://$($env:access_token):x-oauth-basic@github.com`n"
  - git config --global user.email "%GIT_USER_EMAIL%"
  - git config --global user.name "%GIT_USER_NAME%"
  - git clone --depth 5 -q --branch=%TARGET_BRANCH% %STATIC_SITE_REPO% %TEMP%\static-site
  - cd %TEMP%\static-site\gallery
  - python build.py

on_success:
  - echo %random% > .insure-to-commit
  - git add -A
  - git commit -m "Update Static Site"
  - git push origin %TARGET_BRANCH%
  - appveyor AddMessage "Static Site Updated"