name: build gallery

on:
  push:
    branches:
    - master
    paths:
    - gallery/**
env:
  TZ: Asia/Shanghai

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
      with:
        submodules: true
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Pillow opencv-python
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: run build.py
      run: |
        cd gallery
        python build.py
    - name: commit
      run: |
        git config --global user.email bot
        git config --global user.name bot
        git add .
        git commit -m "auto build gallery" -a
      continue-on-error: true
    - name: Push changes  
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.G_PUSH}}
      continue-on-error: true
